import { useSelector } from "react-redux";
import {
  Sparkles,
  ClipboardList,
  Target,
  Mail,
  AlertTriangle,
  Copy,
  Download,
} from "lucide-react";

export default function AIResponse() {
  const aiResponse = useSelector(
    (state) => state.interaction.aiResponse
  );

  const getPriorityColor = (priority) => {
    switch ((priority || "").toLowerCase()) {
      case "high":
        return "bg-red-500/20 text-red-300 border border-red-500/30";

      case "medium":
        return "bg-yellow-500/20 text-yellow-300 border border-yellow-500/30";

      case "low":
        return "bg-green-500/20 text-green-300 border border-green-500/30";

      default:
        return "bg-cyan-500/20 text-cyan-300 border border-cyan-500/30";
    }
  };

  const copyEmail = () => {
    if (!aiResponse?.follow_up_email) return;

    navigator.clipboard.writeText(aiResponse.follow_up_email);

    alert("Follow-up email copied successfully!");
  };

  const downloadReport = () => {
    if (!aiResponse) return;

    const report = `
AI CLINICAL REPORT

==================================

Interaction Summary
----------------------------------
${aiResponse.summary}

Recommended Next Action
----------------------------------
${aiResponse.next_action}

Follow-up Email
----------------------------------
${aiResponse.follow_up_email}

Priority
----------------------------------
${aiResponse.priority}

==================================
Generated by AI First CRM
`;

    const blob = new Blob([report], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;
    a.download = "AI_Clinical_Report.txt";
    a.click();

    URL.revokeObjectURL(url);
  };

  if (!aiResponse) {
    return (
      <div className="bg-white/10 backdrop-blur-xl border border-white/10 rounded-3xl p-8">

        <div className="flex items-center gap-3 mb-8">

          <Sparkles className="text-cyan-400" size={32} />

          <h2 className="text-3xl font-bold text-white">
            AI Clinical Assistant
          </h2>

        </div>

        <div className="bg-slate-800/40 rounded-2xl p-6 border border-slate-700">

          <p className="text-slate-300 text-lg mb-6">
            Generate an interaction to receive intelligent AI-powered
            healthcare insights.
          </p>

          <div className="grid grid-cols-2 gap-4">

            <div className="bg-slate-900/50 rounded-xl p-4 text-slate-300">
              📋 Smart Interaction Summary
            </div>

            <div className="bg-slate-900/50 rounded-xl p-4 text-slate-300">
              🎯 Recommended Next Action
            </div>

            <div className="bg-slate-900/50 rounded-xl p-4 text-slate-300">
              📧 Professional Follow-up Email
            </div>

            <div className="bg-slate-900/50 rounded-xl p-4 text-slate-300">
              🚨 AI Priority Assessment
            </div>

          </div>

          <p className="text-center text-cyan-400 mt-8 text-sm">
            Powered by LangGraph • Groq • FastAPI
          </p>

        </div>

      </div>
    );
  }

  return (
 <div
  id="ai-panel"
  className="bg-white/10 backdrop-blur-xl border border-white/10 rounded-3xl p-8"
>

      <div className="flex items-center justify-between mb-8">

        <div className="flex items-center gap-3">

          <Sparkles className="text-cyan-400" size={32} />

          <h2 className="text-3xl font-bold text-white">
            AI Clinical Assistant
          </h2>

        </div>

        <button
          onClick={downloadReport}
          className="flex items-center gap-2 bg-cyan-500 hover:bg-cyan-400 px-4 py-2 rounded-xl text-white transition"
        >
          <Download size={18} />
          Report
        </button>

      </div>

      <div className="space-y-5">

        <div className="bg-slate-800/50 border-l-4 border-cyan-400 rounded-2xl p-5 hover:bg-slate-800/70 transition">

          <h3 className="flex items-center gap-2 text-cyan-400 font-bold mb-3">
            <ClipboardList size={20} />
            Interaction Summary
          </h3>

          <p className="text-slate-200 leading-7">
            {aiResponse.summary}
          </p>

        </div>

        <div className="bg-slate-800/50 border-l-4 border-green-400 rounded-2xl p-5 hover:bg-slate-800/70 transition">

          <h3 className="flex items-center gap-2 text-green-400 font-bold mb-3">
            <Target size={20} />
            Recommended Next Action
          </h3>

          <p className="text-slate-200 leading-7">
            {aiResponse.next_action}
          </p>

        </div>

        <div className="bg-slate-800/50 border-l-4 border-orange-400 rounded-2xl p-5 hover:bg-slate-800/70 transition">

          <div className="flex justify-between items-center mb-3">

            <h3 className="flex items-center gap-2 text-orange-400 font-bold">
              <Mail size={20} />
              Follow-up Email
            </h3>

            <button
              onClick={copyEmail}
              className="flex items-center gap-2 bg-slate-700 hover:bg-slate-600 px-3 py-2 rounded-lg text-white transition"
            >
              <Copy size={16} />
              Copy
            </button>

          </div>

          <p className="text-slate-200 whitespace-pre-wrap leading-7">
            {aiResponse.follow_up_email}
          </p>

        </div>

        <div className="bg-slate-800/50 border-l-4 border-pink-400 rounded-2xl p-5 hover:bg-slate-800/70 transition">

          <h3 className="flex items-center gap-2 text-pink-400 font-bold mb-3">
            <AlertTriangle size={20} />
            Priority Assessment
          </h3>

          <span
            className={`px-5 py-2 rounded-full font-semibold ${getPriorityColor(
              aiResponse.priority
            )}`}
          >
            {aiResponse.priority}
          </span>

        </div>

      </div>

    </div>
  );
}